### ISSUE TITLE
Unable to follow quickstart usage guide or notebook examples due to lack of config.yaml file

### ISSUE THREAD

**Issue by llewis-faculty** [ronigold/TokenSHAP#1]
When attempting to run the quick guide under 'Usage' in the readme, or the TokenShap Examples notebook, I get the following error as I do not have the required config.yaml file:

```
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_11151/850731727.py in <module>
      2 tokenizer_path = "NousResearch/Hermes-2-Theta-Llama-3-8B"
      3 ollama_api_url = "http://localhost:11434"  # Default Ollama API URL
----> 4 tshap = TokenSHAP(model_name, tokenizer_path)

/opt/anaconda/envs/Python3/lib/python3.9/site-packages/token_shap/token_shap.py in __init__(self, model_name, tokenizer_path)
     27         config_path = os.path.join(dir_path, 'config.yaml')
     28 
---> 29         with open(config_path, 'r') as file:
     30             config = yaml.safe_load(file)
     31         self.ollama_api = config['ollama_api_url']

FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda/envs/Python3/lib/python3.9/site-packages/token_shap/config.yaml'
```

Could you please either provide a config.yaml file that can be used by other users to get up and running with this package, or provide instructions in your readme of how to use the package without this?

**Comment by ronigold** [comment]
@llewis-faculty

Thank you for bringing up the issue with the missing config.yaml file.

We've addressed this in the latest release of TokenSHAP (v0.1.1). In this version, the configuration has been simplified, and there's no longer a need for the config.yaml file. Instead, you can pass the necessary parameters directly to the TokenSHAP object upon initialization. Here's how you can use the updated version:

```
model_name = "llama3"
tokenizer_path = "NousResearch/Hermes-2-Theta-Llama-3-8B"
ollama_api_url = "http://localhost:11434"  # Default Ollama API URL
tshap = TokenSHAP(model_name, tokenizer_path, ollama_api_url)
```

The example notebooks have also been updated accordingly to reflect this change. Please update to the latest version using:

`pip install TokenSHAP==0.1.1
`

Let me know if you encounter any further issues.

**Comment by ronigold** [comment]
@llewis-faculty Let me know if it works so I can close the issue

**Comment by ronigold** [comment]
fix in [Fix ollama url](https://github.com/ronigold/TokenSHAP/commit/7ad1e0aaa0bd8bb9a275fdf9c6399fc360db8535)
